# Generated by Django 3.2.20 on 2023-08-01 10:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(blank=True, null=True, upload_to='publication/%Y%m%d/')),
                ('title', models.CharField(max_length=100)),
                ('pb_author', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=12)),
                ('pb_author_url', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=12)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('journal', models.CharField(max_length=100)),
                ('journal_url', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
                ('paper', models.CharField(max_length=100)),
                ('paper_file', models.FileField(blank=True, upload_to='publication/%Y%m%d/')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
