# Generated by Django 3.2.20 on 2023-08-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20230801_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpost',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='publication/%Y%m%d/'),
        ),
    ]
