# Generated by Django 3.2.20 on 2023-08-01 10:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_publicationpost_img_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpost',
            name='pb_author',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=1, size=None),
            preserve_default=False,
        ),
    ]
