# Generated by Django 3.2.20 on 2023-08-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_publicationpost_pb_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpost',
            name='pb_author',
        ),
    ]
