# Generated by Django 3.2.20 on 2023-08-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20230801_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpost',
            name='keywords',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
